services:
  memgraph:
    # database
    image: memgraph/memgraph-mage:1.22.1-memgraph-2.22.1
    container_name: memgraph-mage-curriculum-lens
    ports:
      - "7687:7687"
      - "7444:7444"
    command: [ "--log-level=TRACE", "--memory-limit=72000", "--storage-mode=IN_MEMORY_ANALYTICAL", "--query-execution-timeout-sec=6000" ]
    environment:
      - MEMGRAPH_USER=testuser123
      - MEMGRAPH_PASSWORD=t123
    volumes:
      - ./data:/data
  analyzer:
    # backend and CLI
    build: ./analyzer
    container_name: analyzer
    ports:
      - "6000:6000"
    volumes:
      - ./data:/data
    depends_on:
      - memgraph
    stdin_open: true
    tty: true

  lab:
    # frontend
    image: memgraph/lab:latest
    container_name: memgraph-lab-curriculum-lens
    ports:
      - "3000:3000"
    depends_on:
      - memgraph
    environment:
      - QUICK_CONNECT_MG_HOST=memgraph
      - QUICK_CONNECT_MG_PORT=7687
